"""Added ResetToken Table

Revision ID: 24e183ce0773
Revises: 393515e60d7c
Create Date: 2025-12-31 09:59:31.742113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e183ce0773'
down_revision = '393515e60d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=70), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reset_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reset_token_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reset_token_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_reset_token_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reset_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_reset_token_token'))
        batch_op.drop_index(batch_op.f('ix_reset_token_id'))
        batch_op.drop_index(batch_op.f('ix_reset_token_expires_at'))

    op.drop_table('reset_token')
    # ### end Alembic commands ###
