"""Created a message table for receiving messages

Revision ID: 361045764b17
Revises: 7d78f788b39d
Create Date: 2026-01-15 23:02:12.309421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361045764b17'
down_revision = '7d78f788b39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_id'))

    op.drop_table('message')
    # ### end Alembic commands ###
