"""Added nullable=True to expected_submission section table

Revision ID: 5175712f9bb5
Revises: 9bd9a70db2be
Create Date: 2025-11-20 03:31:28.975282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5175712f9bb5'
down_revision = '9bd9a70db2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('expected_submission',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('expected_submission',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
