"""Activated ondelete in Section table

Revision ID: 64622148ffe6
Revises: 5175712f9bb5
Create Date: 2025-11-20 19:23:16.783283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64622148ffe6'
down_revision = '5175712f9bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_submission_section_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_submission_section_id', 'section', ['section_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submission_section_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_submission_section_id'), 'section', ['section_id'], ['id'])

    # ### end Alembic commands ###
