"""Just added nullable=True to last_login. Forgot initially

Revision ID: 73d8342a0f06
Revises: 36e0976bf4be
Create Date: 2026-01-20 11:07:38.502478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d8342a0f06'
down_revision = '36e0976bf4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
