"""Di slight modifications on the database models

Revision ID: 7cb99b683348
Revises: 73d8342a0f06
Create Date: 2026-01-21 19:22:17.898891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb99b683348'
down_revision = '73d8342a0f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('section_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('section_code',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=25),
               existing_nullable=True)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('mat_no',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('mat_no',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.alter_column('section_code',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('section_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
