"""Added is_admin attribute to the user model

Revision ID: 7d78f788b39d
Revises: 40cd5a001878
Create Date: 2026-01-10 10:42:11.812415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d78f788b39d'
down_revision = '40cd5a001878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
