"""Added used attribute to the ResetToken model

Revision ID: aaa3087ba5b9
Revises: 24e183ce0773
Create Date: 2026-01-01 09:37:11.625994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa3087ba5b9'
down_revision = '24e183ce0773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_token', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###
